services:
  analog_reflector:
    container_name: AnalogReflector
    image: w3fur/analog_reflector:alpine
    restart: unless-stopped
    volumes:
     - /data/AR/Analog_Reflector.json:/data/Analog_Reflector.json
     - /data/AR/users:/app/arRoot/users
     - /data/AR/modes:/app/arRoot/modes
    hostname: AnalogReflector
    networks:
      main:
        ipv4_address: 172.19.40.1
      web:
        ipv4_address: 172.19.50.40
networks:
  main:
    name: main
    external: true
  web:
    name: web
    external: true

